mantisbt:
  image: vimagick/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - mysql
    - postgres
  restart: always

mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  restart: always

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=mantis
    - POSTGRES_PASSWORD=mantis
    - POSTGRES_DB=bugtracker
  restart: always
  ports:
    - "5432:5432"
