mantisbt:
  image: vimagick/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - mysql
  restart: always

mysql:
  image: mysql:latest
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantis
    - MYSQL_PASSWORD=mantis
  restart: always
  ports:
    - "13306:3306"

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
  restart: always
